# Generated by Django 4.1.7 on 2023-04-11 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.cargo'),
        ),
    ]
