# Generated by Django 4.1.7 on 2023-06-04 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_endereco_tipo_feriado_level_feriado_feriado'),
        ('accounts', '0009_alter_token_codtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='endereco',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='home.endereco'),
            preserve_default=False,
        ),
    ]
