# Generated by Django 4.1.7 on 2023-06-09 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_level_feriado_endereco'),
        ('accounts', '0010_users_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.endereco'),
        ),
    ]
