# Generated by Django 4.1.7 on 2023-04-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='nmEscala',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
