# Generated by Django 4.1.7 on 2023-04-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_histregistro_escala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='horaEntM',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escala',
            name='horaEntV',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escala',
            name='horaSaiM',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escala',
            name='horaSaiV',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='histregistro',
            name='bancoHora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='histregistro',
            name='dataReg',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='histregistro',
            name='horaEntM',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='histregistro',
            name='horaEntV',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='histregistro',
            name='horaSaiM',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='histregistro',
            name='horaSaiV',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
