# Generated by Django 4.1.7 on 2023-04-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_sitreg_histregistro_sitapr'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='domingo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escala',
            name='quarta',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escala',
            name='quinta',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escala',
            name='sabado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escala',
            name='segunda',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escala',
            name='sexta',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escala',
            name='terca',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
