# Generated by Django 4.1.7 on 2023-04-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_histregistro_sitapr'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='dataExtra',
            field=models.DateField(blank=True, null=True),
        ),
    ]
