# Generated by Django 4.1.7 on 2023-04-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_horaextra_dataextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='sitApr',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
