# Generated by Django 4.1.7 on 2023-04-11 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_horaextra_sitapr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaextra',
            name='userLib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userLib', to=settings.AUTH_USER_MODEL),
        ),
    ]
