# Generated by Django 4.1.7 on 2023-04-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_horaextra_userlib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaextra',
            name='sitApr',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
