# Generated by Django 4.1.7 on 2023-04-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_horaextra_sitapr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histregistro',
            name='bancoHora',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
