# Generated by Django 4.1.7 on 2023-04-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_histregistro_bancohora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histregistro',
            old_name='bancoHora',
            new_name='bancoHoraMin',
        ),
    ]
