# Generated by Django 4.1.7 on 2023-04-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_bancohora_histregistro_bancohoramin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histregistro',
            name='bancoHoraMin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
