# Generated by Django 4.1.7 on 2023-05-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_justificativa_txtjust'),
    ]

    operations = [
        migrations.AddField(
            model_name='histregistro',
            name='justificativa',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='home.justificativa'),
            preserve_default=False,
        ),
    ]
