# Generated by Django 4.1.7 on 2023-05-06 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_histregistro_justificativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histregistro',
            name='justificativa',
        ),
        migrations.AddField(
            model_name='justificativa',
            name='histRegistro',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.DO_NOTHING, to='home.histregistro'),
            preserve_default=False,
        ),
    ]
