# Generated by Django 4.1.7 on 2023-05-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_histregistro_justificativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histregistro',
            name='sitAPR',
            field=models.CharField(default='PEN', max_length=3),
        ),
    ]
