# Generated by Django 4.1.7 on 2023-05-10 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_histregistro_altent1_histregistro_altent3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificativa',
            name='histRegistro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Justificativa', to='home.histregistro'),
        ),
    ]
