# Generated by Django 4.1.7 on 2023-05-10 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_justificativa_histregistro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justificativa',
            name='histRegistro',
        ),
        migrations.AddField(
            model_name='histregistro',
            name='justificativas',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='HistRegistro', to='home.justificativa'),
            preserve_default=False,
        ),
    ]
