# Generated by Django 4.1.7 on 2023-05-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_histregistro_justificativas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histregistro',
            name='justificativas',
            field=models.ManyToManyField(blank=True, to='home.justificativa'),
        ),
    ]
