# Generated by Django 4.1.7 on 2023-05-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_histregistro_justificativas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histregistro',
            name='justificativas',
            field=models.ManyToManyField(to='home.justificativa'),
        ),
    ]
