# Generated by Django 4.1.7 on 2023-05-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_histregistro_justificativas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histregistro',
            name='bancoHoraMin',
        ),
    ]
