# Generated by Django 4.1.7 on 2023-05-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_histregistro_bancohoramin'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='justificativas',
            field=models.ManyToManyField(to='home.justificativa'),
        ),
    ]
