# Generated by Django 4.1.7 on 2023-06-04 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_horaextra_sitapr_horaextra_altent1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=255)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('cep', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Endereco',
                'verbose_name_plural': 'Enderecos',
                'db_table': 'endereco',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmTipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo_Feriado',
                'verbose_name_plural': 'Tipos_de_Feriados',
                'db_table': 'tipo_feriado',
            },
        ),
        migrations.CreateModel(
            name='Level_Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmLevel', models.CharField(max_length=255)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.endereco')),
            ],
            options={
                'verbose_name': 'Level_Feriado',
                'verbose_name_plural': 'Leveis_de_Feriados',
                'db_table': 'level_feriado',
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nome', models.CharField(max_length=255)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.level_feriado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.tipo_feriado')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'db_table': 'feriado',
            },
        ),
    ]
