# Generated by Django 4.1.7 on 2023-06-04 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_endereco_tipo_feriado_level_feriado_feriado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level_feriado',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.endereco'),
        ),
    ]
