# Generated by Django 4.1.7 on 2023-06-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_level_feriado_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='histregistro',
            name='obsSup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='obsSup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
