# Generated by Django 4.1.7 on 2023-06-11 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0035_rename_datalib_horaextra_dataapr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histregistro',
            old_name='dataApr',
            new_name='dataAlt',
        ),
        migrations.RenameField(
            model_name='horaextra',
            old_name='dataApr',
            new_name='dataAlt',
        ),
        migrations.RemoveField(
            model_name='histregistro',
            name='userApr',
        ),
        migrations.RemoveField(
            model_name='horaextra',
            name='userAprHe',
        ),
        migrations.AddField(
            model_name='histregistro',
            name='userAlt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userAlt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='userAltHe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userAltHe', to=settings.AUTH_USER_MODEL),
        ),
    ]
